# Optional timing scopes in generated build copies; upstream files stay intact.
# Fail closed if the pinned source signatures no longer match.
function(oft_add_scope name phase)
    string(REGEX MATCH "(int32_t|void) ${name} \\([^;{]*\\) \\{" signature "${profile_source}")
    if(NOT signature)
        message(FATAL_ERROR "OpenH264 profile signature missing: ${name}")
    endif()
    string(REPLACE "${signature}" "${signature}\n  OftH264Scope oft_profile_scope(${phase});" profile_source "${profile_source}")
    set(profile_source "${profile_source}" PARENT_SCOPE)
endfunction()
foreach(stem decode_slice deblocking decoder)
    set(original "${CMAKE_CURRENT_SOURCE_DIR}/vendor/codec/decoder/core/src/${stem}.cpp")
    file(READ "${original}" profile_source)
    if(stem STREQUAL "decode_slice")
        oft_add_scope(WelsDecodeMbCabacISliceBaseMode0 OFT_H264_CABAC)
        oft_add_scope(WelsDecodeMbCavlcISlice OFT_H264_CAVLC)
        oft_add_scope(WelsMbIntraPredictionConstruction OFT_H264_INTRA)
    elseif(stem STREQUAL "deblocking")
        oft_add_scope(WelsDeblockingFilterSlice OFT_H264_DEBLOCK)
        oft_add_scope(WelsDeblockingFilterMB OFT_H264_DEBLOCK)
    elseif(stem STREQUAL "decoder")
        if("$ENV{OFT_NO_EC_SPARE}" STREQUAL "1")
            message(FATAL_ERROR "Rejected experiment: two-picture pool causes PrefetchPic failure; retain upstream reserve")
        endif()
        set(marker "pCtx->iPicQueueNumber = iPicQueueSize;")
        string(FIND "${profile_source}" "${marker}" found)
        if(found LESS 0)
            message(FATAL_ERROR "Decoder memory-layout marker changed")
        endif()
        string(REPLACE "${marker}" "${marker}\n  if (!pCtx->bHaveGotMemory) printf(\"OFT_H264_LAYOUT refs=%d pictures=%d width=%d height=%d\\n\", pCtx->pSps ? (int)pCtx->pSps->iNumRefFrames : -1, (int)iPicQueueSize, (int)kiPicWidth, (int)kiPicHeight);" profile_source "${profile_source}")
    endif()
    set(generated "${CMAKE_CURRENT_BINARY_DIR}/profile_${stem}.cpp")
    set(profile_source "#include \"oft_profile.h\"\n${profile_source}")
    set(previous "")
    if(EXISTS "${generated}")
        file(READ "${generated}" previous)
    endif()
    if(NOT previous STREQUAL profile_source)
        file(WRITE "${generated}" "${profile_source}")
    endif()
    list(REMOVE_ITEM decoder "${original}")
    list(APPEND decoder "${generated}")
endforeach()
if("$ENV{OFT_RESIDUAL_IRAM}" STREQUAL "1")
    set(original "${CMAKE_CURRENT_SOURCE_DIR}/vendor/codec/decoder/core/src/parse_mb_syn_cabac.cpp")
    file(READ "${original}" residual_source)
    foreach(name ParseCbfInfoCabac ParseSignificantMapCabac ParseSignificantCoeffCabac ParseResidualBlockCabac8x8 ParseResidualBlockCabac)
        set(signature "int32_t ${name} (")
        string(FIND "${residual_source}" "${signature}" found)
        if(found LESS 0)
            message(FATAL_ERROR "Residual signature missing: ${name}")
        endif()
        string(REPLACE "${signature}" "IRAM_ATTR ${signature}" residual_source "${residual_source}")
    endforeach()
    set(generated "${CMAKE_CURRENT_BINARY_DIR}/residual_iram.cpp")
    file(WRITE "${generated}" "#include \"esp_attr.h\"\n${residual_source}")
    list(REMOVE_ITEM decoder "${original}")
    list(APPEND decoder "${generated}")
endif()
# Optional experimental arithmetic backend. Rename definitions only; the upstream
# syntax callers keep their normal names and dispatch through the candidate.
if("$ENV{OFT_CABAC32}" STREQUAL "1" OR "$ENV{OFT_CABAC32}" STREQUAL "compact")
    if("$ENV{OFT_CABAC_IRAM}" STREQUAL "1")
        message(FATAL_ERROR "Measure CABAC32 and IRAM separately")
    endif()
    set(original "${CMAKE_CURRENT_SOURCE_DIR}/vendor/codec/decoder/core/src/cabac_decoder.cpp")
    file(READ "${original}" reference_source)
    set(entrypoints DecodeBinCabac DecodeBypassCabac)
    if("$ENV{OFT_CABAC32}" STREQUAL "compact")
        list(APPEND entrypoints InitCabacDecEngineFromBS DecodeTerminateCabac)
        string(REPLACE "void RestoreCabacDecEngineToBS (" "void ReferenceRestoreCabacDecEngineToBS (" reference_source "${reference_source}")
    endif()
    foreach(name ${entrypoints})
        string(FIND "${reference_source}" "int32_t ${name} (" found)
        if(found LESS 0)
            message(FATAL_ERROR "CABAC reference signature changed: ${name}")
        endif()
        string(REPLACE "int32_t ${name} (" "int32_t Reference${name} (" reference_source "${reference_source}")
    endforeach()
    set(reference_file "${CMAKE_CURRENT_BINARY_DIR}/reference_cabac.cpp")
    file(WRITE "${reference_file}" "${reference_source}")
    list(REMOVE_ITEM decoder "${original}")
    if("$ENV{OFT_CABAC32}" STREQUAL "compact")
        list(APPEND decoder "${reference_file}" "${CMAKE_CURRENT_SOURCE_DIR}/compat/cabac_compact.cpp")
    else()
        list(APPEND decoder "${reference_file}" "${CMAKE_CURRENT_SOURCE_DIR}/compat/cabac32.cpp")
    endif()
endif()
# Keep translation units separate: unity compilation measured slower. Place only
# the small arithmetic-decoder routines in IRAM, without changing their bodies.
if(NOT "$ENV{OFT_CABAC_IRAM}" STREQUAL "1")
    return()
endif()
set(cabac "${CMAKE_CURRENT_SOURCE_DIR}/vendor/codec/decoder/core/src/cabac_decoder.cpp")
file(READ "${cabac}" iram_source)
foreach(name Read32BitsCabac DecodeBinCabac DecodeBypassCabac DecodeTerminateCabac DecodeUnaryBinCabac DecodeExpBypassCabac DecodeUEGLevelCabac DecodeUEGMvCabac)
    string(REGEX MATCH "(int32_t|uint32_t) ${name} \\(" signature "${iram_source}")
    if(NOT signature)
        message(FATAL_ERROR "OpenH264 IRAM signature missing: ${name}")
    endif()
    string(REPLACE "${signature}" "IRAM_ATTR ${signature}" iram_source "${iram_source}")
endforeach()
set(iram_file "${CMAKE_CURRENT_BINARY_DIR}/iram_cabac.cpp")
set(iram_source "#include \"esp_attr.h\"\n${iram_source}")
set(previous "")
if(EXISTS "${iram_file}")
    file(READ "${iram_file}" previous)
endif()
if(NOT previous STREQUAL iram_source)
    file(WRITE "${iram_file}" "${iram_source}")
endif()
list(REMOVE_ITEM decoder "${cabac}")
list(APPEND decoder "${iram_file}")
